#!/usr/bin/ash

run_hook() {

        msg "create overlay dir"
        mkdir -p /overlay
        mkdir -p /overlay/lower
        mkdir -p /overlay/upper

        
        rmdir /new_root
        ln -s /overlay/lower /new_root
}

run_latehook() {
        rm /new_root
        mkdir -p /new_root

        msg "→ mounting upperdir to /overlay/upper "
        #checking if overlay tmpfs or other fs
        if [[ "${upperdir}" == "tmpfs" ]]
        {
                mount -o tmpfs tmpfs /overlay/upper
                mkdir -p /overlay/upper/root
                mkdir -p /overlay/upper/work
        }
        msg "→ mounting overlayfs"
        mount -t overlay overlay -o lowerdir=/overlay/lower,upperdir=/overlay/upper/root,workdir=/overlay/upper/work /new_root

        mount -n -o rbind /overlay /new_root/overlay
}