#!/bin/bash

build() {
    add_runscript
}

help() {
    cat <<HELPEOF
This is a custom initcpio hook for mounting the root as an overlayfs,
the basedir should be passed as "root" and the upperdir should be passed
as "upperdir", both as kernel options, the init process should be busybox
and not systemd
HELPEOF
}